server:
  port: 9090
  servlet:
    context-path: /purchase-api

spring:
  flyway:
    baseline-on-migrate: true
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/purchase_db?useSSL=false
    username: root
    password: root
    driverClassName: org.postgresql.Driver

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

feign:
  client:

seller:
  token:
    validity: 60

stock:
  minStock: 1
  maxStock: 10