server:
  port: 9090
  servlet:
    context-path: /purchase-api

spring:
  flyway:
    baseline-on-migrate: true
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    platform: postgres
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


feign:
  client:
    treasury:
      url: https://api.fiscaldata.treasury.gov/services/api/fiscal_service/
      ttl: 60